#!/bin/sh

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
ROOT=$DIR/..

LFR=$ROOT/external/binary_networks/benchmark
#communityDetection=$ROOT/algorithm/build/community_detection
communityDetection=$ROOT/algorithm/script/community_detection_nonoverlapping_iterative.py
communityClassifier=$ROOT/scripts/communityClassifier.py
graphParser=$ROOT/scripts/graphParser.py
NMI=$ROOT/external/NMI/mutual

# write the nmi value to this file
nmiValue=$1
# the percentage of seed nodes
percentage=$2
# the number of rounds for the iterative method
rounds=$3
# the other parameters are passed to the LFR benchmark
LFRParameters="${@:4}"

# the graph output of the lfr
graphLFR="network.dat"
# the community output of the lfr
communitiesLFR="community.dat"
# the graph generated by the graph parser
graph="tmp_graph"
# the community file generated by the graph parser
communities="tmp_communities"
# the seed-node file generated by the graph parser
seedNodes="tmp_seedNodes"
# the affinity output from the c++ algorithm
affinities="tmp_affinies"
# the output from the community classifier
detectedCommunities="tmp_detectedCommunities"

# the multiplication factor for the iterative method
factor=1.1

# fail fast
set -e

echo "=> run LFR"
$LFR $LFRParameters

echo "=> convert the LFR files to our file format and get the seed nodes"
$graphParser -g $graphLFR -G $graph -c $communitiesLFR -C $communities -s $seedNodes -n $percentage

echo "=> perform community detection"
$communityDetection -g $graph -s $seedNodes -a $affinities -r $rounds -f $factor

rm -f $nmiValue
echo "=> classify communities and calculate NMI"
for i in $(seq 0 $(($rounds-1))); do 
    #echo "($(($i+1))/$rounds)"
    $communityClassifier -a ${affinities}_$i -c ${detectedCommunities}_$i
    $NMI $communities ${detectedCommunities}_$i | awk '{print $2 }' >> $nmiValue
done

echo "=> delete files except for $nmiValue"
rm $graphLFR
rm $communitiesLFR
rm $graph
rm $communities
rm $seedNodes
rm ${seedNodes}_$rounds
for i in $(seq 0 $(($rounds-1))); do 
    rm ${seedNodes}_$i
    rm ${affinities}_$i
    rm ${detectedCommunities}_$i
done

echo ""
echo "======================="
echo ""
echo ""
echo "NMI:" 
echo "----"
cat $nmiValue

